# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 16:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import markupfield.fields
import model_utils.fields
import pycones.utils.files
import taggit_autosuggest.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', models.PositiveIntegerField(choices=[(0, 'Draft'), (1, 'Scheduled'), (2, 'Published')], default=0)),
                ('title', models.TextField()),
                ('slug', models.SlugField(blank=True, max_length=128, unique=True)),
                ('content', markupfield.fields.MarkupField(blank=True, default='', rendered_field=True)),
                ('content_markup_type', models.CharField(choices=[('', '--'), ('markdown', 'markdown')], default='markdown', max_length=30)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('_content_rendered', models.TextField(editable=False)),
                ('outstanding_image', models.ImageField(blank=True, null=True, upload_to=pycones.utils.files.UploadToDir('images', random_name=False))),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tags', taggit_autosuggest.managers.TaggableManager(blank=True, help_text='Lista de etiquetas separadas por comas.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Etiquetas')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
