# Generated by Django 2.2.2 on 2019-06-17 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170208_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='_content_ca_rendered',
        ),
        migrations.RemoveField(
            model_name='post',
            name='_content_en_rendered',
        ),
        migrations.RemoveField(
            model_name='post',
            name='_content_es_rendered',
        ),
        migrations.RemoveField(
            model_name='post',
            name='_content_eu_rendered',
        ),
        migrations.RemoveField(
            model_name='post',
            name='_content_gl_rendered',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content_ca',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content_ca_markup_type',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content_en',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content_en_markup_type',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content_es',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content_es_markup_type',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content_eu',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content_eu_markup_type',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content_gl',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content_gl_markup_type',
        ),
        migrations.RemoveField(
            model_name='post',
            name='slug_ca',
        ),
        migrations.RemoveField(
            model_name='post',
            name='slug_en',
        ),
        migrations.RemoveField(
            model_name='post',
            name='slug_es',
        ),
        migrations.RemoveField(
            model_name='post',
            name='slug_eu',
        ),
        migrations.RemoveField(
            model_name='post',
            name='slug_gl',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title_ca',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title_es',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title_eu',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title_gl',
        ),
        migrations.AlterField(
            model_name='post',
            name='_content_rendered',
            field=models.TextField(default='', editable=False),
        ),
    ]
