# Generated by Django 2.2.2 on 2019-11-09 00:24

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [("blog", "0004_auto_20190617_1956")]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content",
            field=martor.models.MartorField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="post",
            name="content_en",
            field=martor.models.MartorField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="content_es",
            field=martor.models.MartorField(blank=True, default="", null=True),
        ),
    ]
