# Generated by Django 2.2.8 on 2020-02-26 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20191109_0024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='_content_en_rendered',
        ),
        migrations.RemoveField(
            model_name='post',
            name='_content_es_rendered',
        ),
        migrations.RemoveField(
            model_name='post',
            name='_content_rendered',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content_en_markup_type',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content_es_markup_type',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content_markup_type',
        ),
    ]
