# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 11:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('type', models.CharField(choices=[('text', 'Text'), ('file', 'File'), ('web_logo', 'Web Logo'), ('simple', 'Simple')], default='simple', max_length=10, verbose_name='type')),
            ],
        ),
        migrations.CreateModel(
            name='BenefitLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_words', models.PositiveIntegerField(blank=True, null=True, verbose_name='max words')),
                ('other_limits', models.CharField(blank=True, max_length=200, verbose_name='other limits')),
                ('benefit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefit_levels', to='sponsorships.Benefit', verbose_name='benefit')),
            ],
            options={
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=100, verbose_name='Sponsor Name')),
                ('external_url', models.URLField(verbose_name='external URL')),
                ('annotation', models.TextField(blank=True, verbose_name='annotation')),
                ('contact_name', models.CharField(max_length=100, verbose_name='Contact Name')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Contact Email')),
                ('active', models.BooleanField(default=False, verbose_name='active')),
                ('applicant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sponsorships', to=settings.AUTH_USER_MODEL, verbose_name='applicant')),
            ],
            options={
                'verbose_name': 'sponsor',
                'verbose_name_plural': 'sponsors',
            },
        ),
        migrations.CreateModel(
            name='SponsorBenefit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('max_words', models.PositiveIntegerField(blank=True, null=True, verbose_name='max words')),
                ('other_limits', models.CharField(blank=True, max_length=200, verbose_name='other limits')),
                ('text', models.TextField(blank=True, verbose_name='text')),
                ('upload', models.FileField(blank=True, upload_to='sponsor_files', verbose_name='file')),
                ('benefit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsor_benefits', to='sponsorships.Benefit', verbose_name='benefit')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsor_benefits', to='sponsorships.Sponsor', verbose_name='sponsor')),
            ],
            options={
                'ordering': ['-active'],
            },
        ),
        migrations.CreateModel(
            name='SponsorLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('order', models.IntegerField(default=0, verbose_name='order')),
                ('cost', models.PositiveIntegerField(verbose_name='cost')),
                ('description', models.TextField(blank=True, help_text='This is private.', verbose_name='description')),
            ],
            options={
                'verbose_name': 'sponsor level',
                'verbose_name_plural': 'sponsor levels',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='sponsor',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sponsorships.SponsorLevel', verbose_name='level'),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='sponsor_logo',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sponsorships.SponsorBenefit'),
        ),
        migrations.AddField(
            model_name='benefitlevel',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefit_levels', to='sponsorships.SponsorLevel', verbose_name='level'),
        ),
    ]
