# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsorships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorlevel',
            name='description_ca',
            field=models.TextField(blank=True, help_text='This is private.', null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='sponsorlevel',
            name='description_en',
            field=models.TextField(blank=True, help_text='This is private.', null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='sponsorlevel',
            name='description_es',
            field=models.TextField(blank=True, help_text='This is private.', null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='sponsorlevel',
            name='description_eu',
            field=models.TextField(blank=True, help_text='This is private.', null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='sponsorlevel',
            name='description_gl',
            field=models.TextField(blank=True, help_text='This is private.', null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='sponsorlevel',
            name='name_ca',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='sponsorlevel',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='sponsorlevel',
            name='name_es',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='sponsorlevel',
            name='name_eu',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='sponsorlevel',
            name='name_gl',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
    ]
