# Generated by Django 2.2.2 on 2019-06-17 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='_description_rendered',
            field=models.TextField(default='', editable=False),
        ),
    ]
