# Generated by Django 2.2.2 on 2019-06-17 19:51

from django.db import migrations, models
import django.utils.timezone
import markupfield.fields
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
                ('text', markupfield.fields.MarkupField(blank=True, default='', help_text='Describe de job offer', rendered_field=True, verbose_name='Text')),
                ('text_es', markupfield.fields.MarkupField(blank=True, default='', help_text='Describe de job offer', null=True, rendered_field=True, verbose_name='Text')),
                ('text_en', markupfield.fields.MarkupField(blank=True, default='', help_text='Describe de job offer', null=True, rendered_field=True, verbose_name='Text')),
                ('text_markup_type', models.CharField(choices=[('', '--'), ('markdown', 'markdown')], default='markdown', max_length=30)),
                ('text_es_markup_type', models.CharField(choices=[('', '--'), ('markdown', 'markdown')], default='markdown', max_length=30)),
                ('text_en_markup_type', models.CharField(choices=[('', '--'), ('markdown', 'markdown')], default='markdown', max_length=30)),
                ('_text_rendered', models.TextField(default='', editable=False)),
                ('_text_es_rendered', models.TextField(default='', editable=False, null=True)),
                ('_text_en_rendered', models.TextField(default='', editable=False, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
