# Generated by Django 2.2.2 on 2019-11-09 01:11

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [("contentchunk", "0002_auto_20190619_1518")]

    operations = [
        migrations.RemoveField(model_name="chunk", name="text_en_markup_type"),
        migrations.RemoveField(model_name="chunk", name="text_es_markup_type"),
        migrations.RemoveField(model_name="chunk", name="text_markup_type"),
        migrations.AlterField(
            model_name="chunk",
            name="text",
            field=martor.models.MartorField(
                blank=True,
                default="",
                help_text="Text in Markdown format",
                verbose_name="Text",
            ),
        ),
        migrations.AlterField(
            model_name="chunk",
            name="text_en",
            field=martor.models.MartorField(
                blank=True,
                default="",
                help_text="Text in Markdown format",
                null=True,
                verbose_name="Text",
            ),
        ),
        migrations.AlterField(
            model_name="chunk",
            name="text_es",
            field=martor.models.MartorField(
                blank=True,
                default="",
                help_text="Text in Markdown format",
                null=True,
                verbose_name="Text",
            ),
        ),
    ]
