# Generated by Django 2.2.2 on 2019-11-09 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentchunk', '0003_auto_20191109_0111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chunk',
            name='_text_en_rendered',
        ),
        migrations.RemoveField(
            model_name='chunk',
            name='_text_es_rendered',
        ),
        migrations.RemoveField(
            model_name='chunk',
            name='_text_rendered',
        ),
    ]
