# Docker-compose file to launch the database used during the development.
version: '2'

volumes:
  db-data:
    driver: local
  db-backups:
    driver: local

services:

  db:
    build: ./compose/postgres
    container_name: pycones-db
    volumes:
      - db-data:/var/lib/postgresql
      - db-backups:/backups
    ports:
      - "5435:5432"
    environment:
      POSTGRES_PASSWORD: potato
      POSTGRES_DB: pycones2017
