# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-10 18:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import markupfield.fields
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sponsorships', '0003_auto_20170209_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('description', markupfield.fields.MarkupField(blank=True, default='', help_text='Describe de job offer', rendered_field=True, verbose_name='Descripción')),
                ('description_markup_type', models.CharField(choices=[('', '--'), ('markdown', 'markdown')], default='markdown', max_length=30)),
                ('application_url', models.URLField(verbose_name='Application URL')),
                ('_description_rendered', models.TextField(editable=False)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employer', to='sponsorships.Sponsor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
