# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-04 08:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import markupfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('speakers', '0002_auto_20170208_1034'),
        ('proposals', '0003_proposal_is_beginners_friendly'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('title_es', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('title_ca', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('title_gl', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('title_eu', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('title_en', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True)),
                ('description', markupfield.fields.MarkupField(blank=True, default='', rendered_field=True)),
                ('description_es', markupfield.fields.MarkupField(blank=True, default='', null=True, rendered_field=True)),
                ('description_ca', markupfield.fields.MarkupField(blank=True, default='', null=True, rendered_field=True)),
                ('description_gl', markupfield.fields.MarkupField(blank=True, default='', null=True, rendered_field=True)),
                ('description_eu', markupfield.fields.MarkupField(blank=True, default='', null=True, rendered_field=True)),
                ('description_en', markupfield.fields.MarkupField(blank=True, default='', null=True, rendered_field=True)),
                ('description_markup_type', models.CharField(choices=[('', '--'), ('markdown', 'markdown')], default='markdown', max_length=30)),
                ('abstract', markupfield.fields.MarkupField(blank=True, default='', rendered_field=True)),
                ('abstract_es', markupfield.fields.MarkupField(blank=True, default='', null=True, rendered_field=True)),
                ('abstract_ca', markupfield.fields.MarkupField(blank=True, default='', null=True, rendered_field=True)),
                ('abstract_gl', markupfield.fields.MarkupField(blank=True, default='', null=True, rendered_field=True)),
                ('abstract_eu', markupfield.fields.MarkupField(blank=True, default='', null=True, rendered_field=True)),
                ('abstract_en', markupfield.fields.MarkupField(blank=True, default='', null=True, rendered_field=True)),
                ('description_es_markup_type', models.CharField(choices=[('', '--'), ('markdown', 'markdown')], default='markdown', max_length=30)),
                ('description_ca_markup_type', models.CharField(choices=[('', '--'), ('markdown', 'markdown')], default='markdown', max_length=30)),
                ('description_gl_markup_type', models.CharField(choices=[('', '--'), ('markdown', 'markdown')], default='markdown', max_length=30)),
                ('description_eu_markup_type', models.CharField(choices=[('', '--'), ('markdown', 'markdown')], default='markdown', max_length=30)),
                ('description_en_markup_type', models.CharField(choices=[('', '--'), ('markdown', 'markdown')], default='markdown', max_length=30)),
                ('_description_rendered', models.TextField(editable=False)),
                ('abstract_markup_type', models.CharField(choices=[('', '--'), ('markdown', 'markdown')], default='markdown', max_length=30)),
                ('abstract_es_markup_type', models.CharField(choices=[('', '--'), ('markdown', 'markdown')], default='markdown', max_length=30)),
                ('abstract_ca_markup_type', models.CharField(choices=[('', '--'), ('markdown', 'markdown')], default='markdown', max_length=30)),
                ('abstract_gl_markup_type', models.CharField(choices=[('', '--'), ('markdown', 'markdown')], default='markdown', max_length=30)),
                ('abstract_eu_markup_type', models.CharField(choices=[('', '--'), ('markdown', 'markdown')], default='markdown', max_length=30)),
                ('abstract_en_markup_type', models.CharField(choices=[('', '--'), ('markdown', 'markdown')], default='markdown', max_length=30)),
                ('_description_es_rendered', models.TextField(editable=False, null=True)),
                ('_description_ca_rendered', models.TextField(editable=False, null=True)),
                ('_description_gl_rendered', models.TextField(editable=False, null=True)),
                ('_description_eu_rendered', models.TextField(editable=False, null=True)),
                ('_description_en_rendered', models.TextField(editable=False, null=True)),
                ('_abstract_rendered', models.TextField(editable=False)),
                ('_abstract_es_rendered', models.TextField(editable=False, null=True)),
                ('_abstract_ca_rendered', models.TextField(editable=False, null=True)),
                ('_abstract_gl_rendered', models.TextField(editable=False, null=True)),
                ('_abstract_eu_rendered', models.TextField(editable=False, null=True)),
                ('_abstract_en_rendered', models.TextField(editable=False, null=True)),
                ('cancelled', models.BooleanField(default=False)),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='video URL')),
                ('keynote_url', models.URLField(blank=True, null=True, verbose_name='URL de la presentación o del código')),
                ('keynote', models.FileField(blank=True, null=True, upload_to='keynotes', verbose_name='Fichero de presentación')),
                ('proposal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='presentation', to='proposals.Proposal')),
            ],
            options={
                'ordering': ['slot'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=65)),
                ('name_es', models.CharField(max_length=65, null=True)),
                ('name_ca', models.CharField(max_length=65, null=True)),
                ('name_gl', models.CharField(max_length=65, null=True)),
                ('name_eu', models.CharField(max_length=65, null=True)),
                ('name_en', models.CharField(max_length=65, null=True)),
                ('order', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('content_override', markupfield.fields.MarkupField(blank=True, rendered_field=True)),
                ('content_override_es', markupfield.fields.MarkupField(blank=True, null=True, rendered_field=True)),
                ('content_override_ca', markupfield.fields.MarkupField(blank=True, null=True, rendered_field=True)),
                ('content_override_gl', markupfield.fields.MarkupField(blank=True, null=True, rendered_field=True)),
                ('content_override_eu', markupfield.fields.MarkupField(blank=True, null=True, rendered_field=True)),
                ('content_override_en', markupfield.fields.MarkupField(blank=True, null=True, rendered_field=True)),
                ('content_override_markup_type', models.CharField(choices=[('', '--'), ('markdown', 'markdown')], default='markdown', max_length=30)),
                ('content_override_es_markup_type', models.CharField(choices=[('', '--'), ('markdown', 'markdown')], default='markdown', max_length=30)),
                ('content_override_ca_markup_type', models.CharField(choices=[('', '--'), ('markdown', 'markdown')], default='markdown', max_length=30)),
                ('content_override_gl_markup_type', models.CharField(choices=[('', '--'), ('markdown', 'markdown')], default='markdown', max_length=30)),
                ('content_override_eu_markup_type', models.CharField(choices=[('', '--'), ('markdown', 'markdown')], default='markdown', max_length=30)),
                ('content_override_en_markup_type', models.CharField(choices=[('', '--'), ('markdown', 'markdown')], default='markdown', max_length=30)),
                ('_content_override_rendered', models.TextField(editable=False)),
                ('_content_override_es_rendered', models.TextField(editable=False, null=True)),
                ('_content_override_ca_rendered', models.TextField(editable=False, null=True)),
                ('_content_override_gl_rendered', models.TextField(editable=False, null=True)),
                ('_content_override_eu_rendered', models.TextField(editable=False, null=True)),
                ('_content_override_en_rendered', models.TextField(editable=False, null=True)),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='video URL')),
                ('keynote_url', models.URLField(blank=True, null=True, verbose_name='keynote URL')),
                ('keynote', models.FileField(blank=True, null=True, upload_to='keynotes', verbose_name='keynote file')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.Day')),
            ],
            options={
                'ordering': ['day', 'start', 'end', 'track__order'],
            },
        ),
        migrations.CreateModel(
            name='SlotKind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('label_es', models.CharField(max_length=50, null=True)),
                ('label_ca', models.CharField(max_length=50, null=True)),
                ('label_gl', models.CharField(max_length=50, null=True)),
                ('label_eu', models.CharField(max_length=50, null=True)),
                ('label_en', models.CharField(max_length=50, null=True)),
                ('class_attr', models.CharField(blank=True, max_length=50, null=True)),
                ('plenary', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=120)),
                ('name_es', models.TextField(max_length=120, null=True)),
                ('name_ca', models.TextField(max_length=120, null=True)),
                ('name_gl', models.TextField(max_length=120, null=True)),
                ('name_eu', models.TextField(max_length=120, null=True)),
                ('name_en', models.TextField(max_length=120, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('day', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedules.Day')),
            ],
        ),
        migrations.AddField(
            model_name='slot',
            name='kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.SlotKind'),
        ),
        migrations.AddField(
            model_name='slot',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='schedules.Room'),
        ),
        migrations.AddField(
            model_name='slot',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='schedules.Track'),
        ),
        migrations.AddField(
            model_name='presentation',
            name='slot',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presentation', to='schedules.Slot'),
        ),
        migrations.AddField(
            model_name='presentation',
            name='speakers',
            field=models.ManyToManyField(related_name='presentations', to='speakers.Speaker'),
        ),
    ]
