# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-05 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slot',
            options={'ordering': ['day', 'start', 'end', 'track__order', 'order']},
        ),
        migrations.AlterField(
            model_name='presentation',
            name='speakers',
            field=models.ManyToManyField(blank=True, related_name='presentations', to='speakers.Speaker'),
        ),
    ]
