# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-17 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0005_auto_20170705_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='language',
            field=models.CharField(blank=True, choices=[('es', 'Español'), ('en', 'Inglés')], max_length=2, null=True, verbose_name='Idioma'),
        ),
    ]
