# Generated by Django 2.2.2 on 2019-06-17 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("schedules", "0006_presentation_language")]

    operations = [
        migrations.AlterField(
            model_name="presentation",
            name="_abstract_en_rendered",
            field=models.TextField(default="", editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="presentation",
            name="_abstract_es_rendered",
            field=models.TextField(default="", editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="presentation",
            name="_abstract_rendered",
            field=models.TextField(default="", editable=False),
        ),
        migrations.AlterField(
            model_name="presentation",
            name="_description_en_rendered",
            field=models.TextField(default="", editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="presentation",
            name="_description_es_rendered",
            field=models.TextField(default="", editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="presentation",
            name="_description_rendered",
            field=models.TextField(default="", editable=False),
        ),
    ]
