# Generated by Django 2.2.2 on 2019-11-09 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("schedules", "0009_auto_20190619_1518")]

    operations = []

