# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-22 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='score',
            field=models.FloatField(blank=True, help_text='Puntuación del 1.0 al 4.0', null=True),
        ),
    ]
