# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-22 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewers', '0002_review_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='interest',
        ),
        migrations.RemoveField(
            model_name='review',
            name='newness',
        ),
        migrations.RemoveField(
            model_name='review',
            name='relevance',
        ),
        migrations.AlterField(
            model_name='review',
            name='conflict',
            field=models.BooleanField(default=False, verbose_name='¿Existe un conflicto de intereses?'),
        ),
    ]
