# Generated by Django 2.2.2 on 2019-09-03 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tshirts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tshirtbooking',
            name='nif',
            field=models.CharField(blank=True, help_text='Ingresa tu NIF/NIE', max_length=9, verbose_name='NIF/NIE'),
        ),
        migrations.AlterField(
            model_name='tshirtbooking',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Hombre'), ('F', 'Mujer')], max_length=1, verbose_name='Corte'),
        ),
        migrations.AlterField(
            model_name='tshirtbooking',
            name='tshirt_size',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')], max_length=3, verbose_name='Medida'),
        ),
    ]
