# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 10:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sponsorships', '0002_auto_20170208_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='applicant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sponsorships', to=settings.AUTH_USER_MODEL, verbose_name='applicant'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Contact Email'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='contact_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Contact Name'),
        ),
    ]
