# Generated by Django 2.2.2 on 2019-06-17 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("sponsorships", "0003_auto_20170209_1025")]

    operations = []

