# Generated by Django 2.2.2 on 2019-06-17 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("sponsorships", "0004_auto_20190617_1951")]

    operations = []

