# Generated by Django 2.2.2 on 2019-11-09 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("sponsorships", "0007_auto_20190627_2223")]

    operations = []

