# Generated by Django 2.2.2 on 2019-06-19 15:18

from django.db import migrations
import markupfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contentchunk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chunk',
            name='text',
            field=markupfield.fields.MarkupField(blank=True, default='', help_text='Text in Markdown format', rendered_field=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='chunk',
            name='text_en',
            field=markupfield.fields.MarkupField(blank=True, default='', help_text='Text in Markdown format', null=True, rendered_field=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='chunk',
            name='text_es',
            field=markupfield.fields.MarkupField(blank=True, default='', help_text='Text in Markdown format', null=True, rendered_field=True, verbose_name='Text'),
        ),
    ]
