# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 10:34
from __future__ import unicode_literals

from django.db import migrations, models
import markupfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='_biography_ca_rendered',
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='speaker',
            name='_biography_en_rendered',
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='speaker',
            name='_biography_es_rendered',
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='speaker',
            name='_biography_eu_rendered',
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='speaker',
            name='_biography_gl_rendered',
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='speaker',
            name='biography_ca',
            field=markupfield.fields.MarkupField(blank=True, default='', help_text="Unas palabras sobre ti. Edita usando <a href='http://warpedvisions.org/projects/markdown-cheat-sheet/target='_blank'>Markdown</a>.", null=True, rendered_field=True, verbose_name='Biografía'),
        ),
        migrations.AddField(
            model_name='speaker',
            name='biography_ca_markup_type',
            field=models.CharField(choices=[('', '--'), ('markdown', 'markdown')], default='markdown', max_length=30),
        ),
        migrations.AddField(
            model_name='speaker',
            name='biography_en',
            field=markupfield.fields.MarkupField(blank=True, default='', help_text="Unas palabras sobre ti. Edita usando <a href='http://warpedvisions.org/projects/markdown-cheat-sheet/target='_blank'>Markdown</a>.", null=True, rendered_field=True, verbose_name='Biografía'),
        ),
        migrations.AddField(
            model_name='speaker',
            name='biography_en_markup_type',
            field=models.CharField(choices=[('', '--'), ('markdown', 'markdown')], default='markdown', max_length=30),
        ),
        migrations.AddField(
            model_name='speaker',
            name='biography_es',
            field=markupfield.fields.MarkupField(blank=True, default='', help_text="Unas palabras sobre ti. Edita usando <a href='http://warpedvisions.org/projects/markdown-cheat-sheet/target='_blank'>Markdown</a>.", null=True, rendered_field=True, verbose_name='Biografía'),
        ),
        migrations.AddField(
            model_name='speaker',
            name='biography_es_markup_type',
            field=models.CharField(choices=[('', '--'), ('markdown', 'markdown')], default='markdown', max_length=30),
        ),
        migrations.AddField(
            model_name='speaker',
            name='biography_eu',
            field=markupfield.fields.MarkupField(blank=True, default='', help_text="Unas palabras sobre ti. Edita usando <a href='http://warpedvisions.org/projects/markdown-cheat-sheet/target='_blank'>Markdown</a>.", null=True, rendered_field=True, verbose_name='Biografía'),
        ),
        migrations.AddField(
            model_name='speaker',
            name='biography_eu_markup_type',
            field=models.CharField(choices=[('', '--'), ('markdown', 'markdown')], default='markdown', max_length=30),
        ),
        migrations.AddField(
            model_name='speaker',
            name='biography_gl',
            field=markupfield.fields.MarkupField(blank=True, default='', help_text="Unas palabras sobre ti. Edita usando <a href='http://warpedvisions.org/projects/markdown-cheat-sheet/target='_blank'>Markdown</a>.", null=True, rendered_field=True, verbose_name='Biografía'),
        ),
        migrations.AddField(
            model_name='speaker',
            name='biography_gl_markup_type',
            field=models.CharField(choices=[('', '--'), ('markdown', 'markdown')], default='markdown', max_length=30),
        ),
    ]
