# Generated by Django 2.2.2 on 2019-06-17 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("speakers", "0002_auto_20170208_1034")]

    operations = [
        migrations.AlterField(
            model_name="speaker",
            name="_biography_en_rendered",
            field=models.TextField(default="", editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="speaker",
            name="_biography_es_rendered",
            field=models.TextField(default="", editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="speaker",
            name="_biography_rendered",
            field=models.TextField(default="", editable=False),
        ),
    ]
