# Generated by Django 2.2.2 on 2019-06-17 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("speakers", "0003_auto_20190617_1951")]

    operations = []

