# Generated by Django 2.2.2 on 2019-11-09 13:32

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [("speakers", "0006_auto_20191109_0024")]

    operations = [
        migrations.RemoveField(model_name="speaker", name="_biography_en_rendered"),
        migrations.RemoveField(model_name="speaker", name="_biography_es_rendered"),
        migrations.RemoveField(model_name="speaker", name="_biography_rendered"),
        migrations.RemoveField(model_name="speaker", name="biography_en_markup_type"),
        migrations.RemoveField(model_name="speaker", name="biography_es_markup_type"),
        migrations.RemoveField(model_name="speaker", name="biography_markup_type"),
        migrations.AlterField(
            model_name="speaker",
            name="biography",
            field=martor.models.MartorField(
                blank=True,
                default="",
                help_text="Unas palabras sobre ti. Edita usando Markdown</a>.",
                verbose_name="Biografía",
            ),
        ),
        migrations.AlterField(
            model_name="speaker",
            name="biography_en",
            field=martor.models.MartorField(
                blank=True,
                default="",
                help_text="Unas palabras sobre ti. Edita usando Markdown</a>.",
                null=True,
                verbose_name="Biografía",
            ),
        ),
        migrations.AlterField(
            model_name="speaker",
            name="biography_es",
            field=martor.models.MartorField(
                blank=True,
                default="",
                help_text="Unas palabras sobre ti. Edita usando Markdown.",
                null=True,
                verbose_name="Biografía",
            ),
        ),
    ]
