# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 10:34
from __future__ import unicode_literals

from django.db import migrations, models
import markupfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='_abstract_ca_rendered',
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='_abstract_en_rendered',
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='_abstract_es_rendered',
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='_abstract_eu_rendered',
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='_abstract_gl_rendered',
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='_additional_notes_ca_rendered',
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='_additional_notes_en_rendered',
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='_additional_notes_es_rendered',
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='_additional_notes_eu_rendered',
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='_additional_notes_gl_rendered',
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='abstract_ca',
            field=markupfield.fields.MarkupField(blank=True, default='', help_text="Resumen detallado. Se hará pública si la propuesta se acepta. Edita usando <a href='http://daringfireball.net/projects/markdown/basics' target='_blank'>Markdown</a>.", null=True, rendered_field=True, verbose_name='Resumen detallado'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='abstract_ca_markup_type',
            field=models.CharField(choices=[('', '--'), ('markdown', 'markdown')], default='markdown', max_length=30),
        ),
        migrations.AddField(
            model_name='proposal',
            name='abstract_en',
            field=markupfield.fields.MarkupField(blank=True, default='', help_text="Resumen detallado. Se hará pública si la propuesta se acepta. Edita usando <a href='http://daringfireball.net/projects/markdown/basics' target='_blank'>Markdown</a>.", null=True, rendered_field=True, verbose_name='Resumen detallado'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='abstract_en_markup_type',
            field=models.CharField(choices=[('', '--'), ('markdown', 'markdown')], default='markdown', max_length=30),
        ),
        migrations.AddField(
            model_name='proposal',
            name='abstract_es',
            field=markupfield.fields.MarkupField(blank=True, default='', help_text="Resumen detallado. Se hará pública si la propuesta se acepta. Edita usando <a href='http://daringfireball.net/projects/markdown/basics' target='_blank'>Markdown</a>.", null=True, rendered_field=True, verbose_name='Resumen detallado'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='abstract_es_markup_type',
            field=models.CharField(choices=[('', '--'), ('markdown', 'markdown')], default='markdown', max_length=30),
        ),
        migrations.AddField(
            model_name='proposal',
            name='abstract_eu',
            field=markupfield.fields.MarkupField(blank=True, default='', help_text="Resumen detallado. Se hará pública si la propuesta se acepta. Edita usando <a href='http://daringfireball.net/projects/markdown/basics' target='_blank'>Markdown</a>.", null=True, rendered_field=True, verbose_name='Resumen detallado'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='abstract_eu_markup_type',
            field=models.CharField(choices=[('', '--'), ('markdown', 'markdown')], default='markdown', max_length=30),
        ),
        migrations.AddField(
            model_name='proposal',
            name='abstract_gl',
            field=markupfield.fields.MarkupField(blank=True, default='', help_text="Resumen detallado. Se hará pública si la propuesta se acepta. Edita usando <a href='http://daringfireball.net/projects/markdown/basics' target='_blank'>Markdown</a>.", null=True, rendered_field=True, verbose_name='Resumen detallado'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='abstract_gl_markup_type',
            field=models.CharField(choices=[('', '--'), ('markdown', 'markdown')], default='markdown', max_length=30),
        ),
        migrations.AddField(
            model_name='proposal',
            name='additional_notes_ca',
            field=markupfield.fields.MarkupField(blank=True, default='', help_text="Cualquier cosa que te gustaría hacer saber a los revisores para que la tengan en cuenta al ahora de hacer la selección. Esto no se hará público. Edita usando <a href='http://daringfireball.net/projects/markdown/basics' target='_blank'>Markdown</a>.", null=True, rendered_field=True, verbose_name='Notas adicionales'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='additional_notes_ca_markup_type',
            field=models.CharField(choices=[('', '--'), ('markdown', 'markdown')], default='markdown', max_length=30),
        ),
        migrations.AddField(
            model_name='proposal',
            name='additional_notes_en',
            field=markupfield.fields.MarkupField(blank=True, default='', help_text="Cualquier cosa que te gustaría hacer saber a los revisores para que la tengan en cuenta al ahora de hacer la selección. Esto no se hará público. Edita usando <a href='http://daringfireball.net/projects/markdown/basics' target='_blank'>Markdown</a>.", null=True, rendered_field=True, verbose_name='Notas adicionales'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='additional_notes_en_markup_type',
            field=models.CharField(choices=[('', '--'), ('markdown', 'markdown')], default='markdown', max_length=30),
        ),
        migrations.AddField(
            model_name='proposal',
            name='additional_notes_es',
            field=markupfield.fields.MarkupField(blank=True, default='', help_text="Cualquier cosa que te gustaría hacer saber a los revisores para que la tengan en cuenta al ahora de hacer la selección. Esto no se hará público. Edita usando <a href='http://daringfireball.net/projects/markdown/basics' target='_blank'>Markdown</a>.", null=True, rendered_field=True, verbose_name='Notas adicionales'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='additional_notes_es_markup_type',
            field=models.CharField(choices=[('', '--'), ('markdown', 'markdown')], default='markdown', max_length=30),
        ),
        migrations.AddField(
            model_name='proposal',
            name='additional_notes_eu',
            field=markupfield.fields.MarkupField(blank=True, default='', help_text="Cualquier cosa que te gustaría hacer saber a los revisores para que la tengan en cuenta al ahora de hacer la selección. Esto no se hará público. Edita usando <a href='http://daringfireball.net/projects/markdown/basics' target='_blank'>Markdown</a>.", null=True, rendered_field=True, verbose_name='Notas adicionales'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='additional_notes_eu_markup_type',
            field=models.CharField(choices=[('', '--'), ('markdown', 'markdown')], default='markdown', max_length=30),
        ),
        migrations.AddField(
            model_name='proposal',
            name='additional_notes_gl',
            field=markupfield.fields.MarkupField(blank=True, default='', help_text="Cualquier cosa que te gustaría hacer saber a los revisores para que la tengan en cuenta al ahora de hacer la selección. Esto no se hará público. Edita usando <a href='http://daringfireball.net/projects/markdown/basics' target='_blank'>Markdown</a>.", null=True, rendered_field=True, verbose_name='Notas adicionales'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='additional_notes_gl_markup_type',
            field=models.CharField(choices=[('', '--'), ('markdown', 'markdown')], default='markdown', max_length=30),
        ),
        migrations.AddField(
            model_name='proposal',
            name='description_ca',
            field=models.TextField(help_text='Si tu propuesta se acepta esto se hará público, y se incluirá en el programa. Debería ser un párrafo, con un máximo de 500 caracteres.', max_length=500, null=True, verbose_name='Breve descripción'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='description_en',
            field=models.TextField(help_text='Si tu propuesta se acepta esto se hará público, y se incluirá en el programa. Debería ser un párrafo, con un máximo de 500 caracteres.', max_length=500, null=True, verbose_name='Breve descripción'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='description_es',
            field=models.TextField(help_text='Si tu propuesta se acepta esto se hará público, y se incluirá en el programa. Debería ser un párrafo, con un máximo de 500 caracteres.', max_length=500, null=True, verbose_name='Breve descripción'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='description_eu',
            field=models.TextField(help_text='Si tu propuesta se acepta esto se hará público, y se incluirá en el programa. Debería ser un párrafo, con un máximo de 500 caracteres.', max_length=500, null=True, verbose_name='Breve descripción'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='description_gl',
            field=models.TextField(help_text='Si tu propuesta se acepta esto se hará público, y se incluirá en el programa. Debería ser un párrafo, con un máximo de 500 caracteres.', max_length=500, null=True, verbose_name='Breve descripción'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='title_ca',
            field=models.CharField(max_length=100, null=True, verbose_name='Título'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Título'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='title_es',
            field=models.CharField(max_length=100, null=True, verbose_name='Título'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='title_eu',
            field=models.CharField(max_length=100, null=True, verbose_name='Título'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='title_gl',
            field=models.CharField(max_length=100, null=True, verbose_name='Título'),
        ),
        migrations.AddField(
            model_name='proposalkind',
            name='name_ca',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='proposalkind',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='proposalkind',
            name='name_es',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='proposalkind',
            name='name_eu',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='proposalkind',
            name='name_gl',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='proposalkind',
            name='slug_ca',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='proposalkind',
            name='slug_en',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='proposalkind',
            name='slug_es',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='proposalkind',
            name='slug_eu',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='proposalkind',
            name='slug_gl',
            field=models.SlugField(null=True),
        ),
    ]
