# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-07 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0002_auto_20170208_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='is_beginners_friendly',
            field=models.BooleanField(default=False, verbose_name='¿Es apta para principiantes?'),
        ),
    ]
