# Generated by Django 2.2.2 on 2019-11-09 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("proposals", "0007_auto_20191109_1107")]

    operations = [
        migrations.RemoveField(model_name="proposal", name="_abstract_en_rendered"),
        migrations.RemoveField(model_name="proposal", name="_abstract_es_rendered"),
        migrations.RemoveField(
            model_name="proposal", name="_additional_notes_en_rendered"
        ),
        migrations.RemoveField(
            model_name="proposal", name="_additional_notes_es_rendered"
        ),
    ]

