# Generated by Django 2.2.2 on 2019-11-09 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("proposals", "0008_auto_20191109_1308")]

    operations = [
        migrations.RemoveField(model_name="proposal", name="_abstract_rendered"),
        migrations.RemoveField(
            model_name="proposal", name="_additional_notes_rendered"
        ),
    ]

