# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 10:34
from __future__ import unicode_literals

from django.db import migrations, models
import markupfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='_content_ca_rendered',
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='_content_en_rendered',
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='_content_es_rendered',
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='_content_eu_rendered',
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='_content_gl_rendered',
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_ca',
            field=markupfield.fields.MarkupField(blank=True, default='', null=True, rendered_field=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_ca_markup_type',
            field=models.CharField(choices=[('', '--'), ('markdown', 'markdown')], default='markdown', max_length=30),
        ),
        migrations.AddField(
            model_name='post',
            name='content_en',
            field=markupfield.fields.MarkupField(blank=True, default='', null=True, rendered_field=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_en_markup_type',
            field=models.CharField(choices=[('', '--'), ('markdown', 'markdown')], default='markdown', max_length=30),
        ),
        migrations.AddField(
            model_name='post',
            name='content_es',
            field=markupfield.fields.MarkupField(blank=True, default='', null=True, rendered_field=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_es_markup_type',
            field=models.CharField(choices=[('', '--'), ('markdown', 'markdown')], default='markdown', max_length=30),
        ),
        migrations.AddField(
            model_name='post',
            name='content_eu',
            field=markupfield.fields.MarkupField(blank=True, default='', null=True, rendered_field=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_eu_markup_type',
            field=models.CharField(choices=[('', '--'), ('markdown', 'markdown')], default='markdown', max_length=30),
        ),
        migrations.AddField(
            model_name='post',
            name='content_gl',
            field=markupfield.fields.MarkupField(blank=True, default='', null=True, rendered_field=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_gl_markup_type',
            field=models.CharField(choices=[('', '--'), ('markdown', 'markdown')], default='markdown', max_length=30),
        ),
        migrations.AddField(
            model_name='post',
            name='slug_ca',
            field=models.SlugField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='post',
            name='slug_en',
            field=models.SlugField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='post',
            name='slug_es',
            field=models.SlugField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='post',
            name='slug_eu',
            field=models.SlugField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='post',
            name='slug_gl',
            field=models.SlugField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_ca',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_eu',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_gl',
            field=models.TextField(null=True),
        ),
    ]
