# Generated by Django 2.2.2 on 2019-06-17 19:56

from django.db import migrations, models
import markupfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190617_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='_content_en_rendered',
            field=models.TextField(default='', editable=False, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='_content_es_rendered',
            field=models.TextField(default='', editable=False, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_en',
            field=markupfield.fields.MarkupField(blank=True, default='', null=True, rendered_field=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_en_markup_type',
            field=models.CharField(choices=[('', '--'), ('markdown', 'markdown')], default='markdown', max_length=30),
        ),
        migrations.AddField(
            model_name='post',
            name='content_es',
            field=markupfield.fields.MarkupField(blank=True, default='', null=True, rendered_field=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_es_markup_type',
            field=models.CharField(choices=[('', '--'), ('markdown', 'markdown')], default='markdown', max_length=30),
        ),
        migrations.AddField(
            model_name='post',
            name='slug_en',
            field=models.SlugField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='post',
            name='slug_es',
            field=models.SlugField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_es',
            field=models.TextField(null=True),
        ),
    ]
