# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-05 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_auto_20170705_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentation',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=100, null=True),
        ),
    ]
