# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-05 21:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0003_auto_20170705_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentation',
            name='proposal',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='presentation', to='proposals.Proposal'),
        ),
    ]
