# Generated by Django 2.2.2 on 2019-06-19 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("schedules", "0008_auto_20190617_1956")]

    operations = []

